WITH RECURSIVE CTE AS(
    SELECT 0 AS NUM # 초기값 설정
    UNION ALL
    SELECT NUM + 1 FROM CTE WHERE NUM < 23 # 반복을 멈추는 조건
) 

SELECT CTE.NUM AS HOUR, COUNT(DATETIME) AS COUNT
FROM CTE
LEFT JOIN ANIMAL_OUTS ON CTE.NUM = HOUR(DATETIME)
GROUP BY CTE.NUM
ORDER BY CTE.NUM;